### ISSUE TITLE
Need a way to handle Pairing the same device after a re-install

### ISSUE THREAD

**Issue by andrewclaus** [pingidentity/pingone-mobile-sdk-android#16]
During testing of pairing Android devices, we have come across a scenario where the user can 
1. install the app
2. pair the device
3. uninstall the app
4. repeat

Each time the user pairs, it adds a new authentication method into the PingOne user. The user can max out their allowed number of paired devices, and when they do, it causes additional issues. (User will receive an error when attempting to pair additional times, if an old pairing is selected during an MFA request then unexpected errors will be received)

On the PingOne iOS SDK, I found a method called PingOne.setDevicePairedAfterReinstall(bool) which allows me to tell PingOne that it should keep the device as paired after a reinstall. This may be slightly less secure, but it solves the issue described above. 

I am unable to find an equivalent to this with the Android SDK.

Does something exist in the Android SDK to either keep the device paired or cleanup the old pairing after a reinstall?
If not, is this something planned to be added? And do you have any other suggested workarounds?

**Comment by segev-ping** [comment]
`setDevicePairedAfterReinstall` is only available on iOS. 
It is not available on Android due to OS limitations. 

There is currently no way to remove an authenticating device from the mobile side. 
In order to remove a device you'll need to remove it from the PingOne portal.

**Comment by andrewclaus** [comment]
Thanks for the quick response @Segev-ping. I will keep this issue open for now until I receive a response from Ping Support on any known workarounds to this problem (from the PingOne side). I will update here with any details to serve as documentation for others to run across this problem.

I understand that we would be able to manually remove devices through the PingOne portal, however this would be cumbersome for us with our large userbase. We are looking for an automated solution that will not impact the user experience.

**Comment by andrewclaus** [comment]
Just a quick update, I have received word from Ping Support that this request has been entered as a product feature internally. Currently no ETA.

**Comment by andrewclaus** [comment]
Quick update, a new update should be rolling out shortly by PingOne that will address my concerns. After this update is released, when a user selects an invalid mobile device, that device will be unpaired from that user.

**Comment by undersieg** [comment]
Maybe in order to have the same method like `setDevicePairedAfterReinstall` on Android side Secure settings could be used, it's only reset during factory reset. e.g.:
`Settings.Secure.getString(applicationContext?.contentResolver, Settings.Secure.ANDROID_ID)`
