### ISSUE TITLE
VULNERABILITY org.jetbrains.kotlin:kotlin-stdlib

### ISSUE THREAD

**Issue by john-li-versent** [pingidentity/pingone-mobile-sdk-android#27]
Detailed paths
Introduced through: com.appmattus.certificatetransparency:certificatetransparency-android@1.0.0 › com.appmattus.certificatetransparency:certificatetransparency@1.0.0 › com.squareup.okhttp3:okhttp@4.9.2 › com.squareup.okio:okio@2.8.0 › org.jetbrains.kotlin:kotlin-stdlib@1.5.31

[SNYK-JAVA-ORGJETBRAINSKOTLIN-2628385](https://app.snyk.io/vuln/SNYK-JAVA-ORGJETBRAINSKOTLIN-2628385)

Overview
[org.jetbrains.kotlin:kotlin-stdlib](https://search.maven.org/artifact/org.jetbrains.kotlin/kotlin-stdlib) is a Kotlin Standard Library for JVM.

Affected versions of this package are vulnerable to Improper Locking due to inability to lock dependencies for Multiplatform Gradle Projects.

Remediation
Upgrade org.jetbrains.kotlin:kotlin-stdlib to version 1.6.0 or higher.

**Comment by amitnadirping** [comment]
The SDK 1.11.0 has version  `org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0` that answers this concern.
