### ISSUE TITLE
Dependency of deprecated firebase-core package

### ISSUE THREAD

**Issue by llucie** [pingidentity/pingone-mobile-sdk-android#33]
I am integrating the ping android SDK in my flutter application.
I added the dependency to ping in my app/build.gradle:

```shell
implementation 'com.pingidentity.pingonemfa:android-sdk:1.10.0'
```

I get the following error while building:

```shell
FAILURE: Build failed with an exception.

* What went wrong:Execution failed for task ':app:checkPreprodDebugAarMetadata'.
 > Could not resolve all files for configuration ':app:preprodDebugRuntimeClasspath'.  
   > Could not find com.google.firebase:firebase-core:.     
Searched in the following locations:       - file:/path/to/project/android/app/libs/firebase-core.jar      
   Required by:         project :app > com.pingidentity.pingonemfa:android-sdk:1.10.0
```

There is a dependency to `firebase-core`. I added the requested jar file in my `libs/` folder (found [here](https://mvnrepository.com/artifact/com.google.firebase/firebase-core/21.1.1)), and I'm able to compile the project.

Therefore, according to the [Firebase documentation](https://firebase.google.com/support/release-notes/android#core_v21-1-1), the firebase-core package is deprecated and no further will be released.

> The firebase-core library is deprecated and no further versions will be released. This SDK included the Firebase SDK for Google Analytics.
> 
> Now, to use Google Analytics or a product that recommends adding Google Analytics, you need to explicitly declare the Analytics dependency: com.google.firebase:firebase-analytics or com.google.firebase:firebase-analytics-ktx.

Is there any plan to replace this dependency with another one, still maintained by firebase?

**Comment by amitnadirping** [comment]
In SDK 1.11.0 the `firebase-core` library was removed. This answers the above concern.

**Comment by amitnadirping** [comment]
issue closed
