### ISSUE TITLE
Google Service Json File is missing

### ISSUE THREAD

**Issue by slashnextSDK** [pingidentity/pingone-mobile-sdk-android#36]
I am trying to run sample app but i am getting this error " File google-services.json is missing. The Google Services Plugin cannot function without it". Can someone please guide me?

**Comment by segev-ping** [comment]
The json file is a prerequisite you download from the firebase developers console. 
Please follow https://github.com/pingidentity/pingone-mobile-sdk-android?tab=readme-ov-file#13-prerequisites-for-using-fcm-push-kit
